# This is a sample .yaml file to be added a repo's /.github/workflows/ folder.
# This file is accessible in the Github UI under the "Actions" tab in the repo and set as a "New Workflow".
# This action runs as a "docker container inside of Github. Each of the "steps" appear in the "Workflow" of the action set in the "Actions" tab in Github.
# Any step or line after comments that contain DEBUG: are not required, but can help troubleshoot any issues. 
name: Github SCP Deploy Action
on:
  push:
    branches:
      # Which branch you want to deploy.
      - main
jobs:
  deploy:
    # Docker base OS to use for the container.
    runs-on: ubuntu-latest
    steps:
    # This step is an pre-defined action created by Github. More references on this can be found here: https://github.com/actions/checkout?tab=readme-ov-file#scenarios
    # This steps is used to "Checkout" the repository, which adds all contents of the repo temporarily to the ~/ directory of the Docker container so we can push files using SCP.
    - name: Check out repository
      uses: actions/checkout@v2
    # Visual verification of that the "Repository secret" we for the action. This "Repository secret" is added in the Github UI under: <Repository> -> "Settings" -> "Secrets and variables" -> "Actions" -> "Repository secrets".
    # Create a "New repository secret" and paste all contents of your ".pem" file into the new "secret".
    - name: Verify SSH Private Key
      env:
          # References the "Repository secret" by its name in Github's UI under <Repository> -> "Settings" -> "Secrets and variables" -> "Actions" -> "Repository secrets".
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # DEBUG: Displays the contents of our "Repository secret" named "SSH_PRIVATE_KEY". The values will be encrypted and display as a series of "***".
        echo "SSH Private Key is: " && 
        echo $SSH_PRIVATE_KEY
    # Step to create a "temporary" ~/.ssh directory to store a temporary .pem key file.
    - name: Create ~/.ssh directory
      run: |
        # Change to the home directory.
        cd ~ &&
        # Create the .ssh directory
        sudo mkdir -p ~/.ssh &&
        # DEBUG: Display the path of the current directory.
        echo "Current directory is: " $(pwd) &&
        # DEBUG: List the files in the directoy.
        echo "Directory contents of " $(pwd) ": " &&
        sudo ls -la
    # Step to create a "temporary" .pem key file called "id_rsa.key" from contents of our "Repository secret" named "SSH_PRIVATE_KEY" to use for SCP file transfer.
    - name: Create SSH Private Key file id_rsa.key
      run: |
        # Create the temporary id_rsa.key file using 'touch'.
        sudo touch ~/.ssh/id_rsa.key &&
        # DEBUG: Change to the home directory.
        cd ~ &&
        # DEBUG: Change to ~/.ssh directory inside home directory.
        cd .ssh &&
        # DEBUG: Display the path of the current directory.
        echo "Current directory is: " $(pwd) &&
        # DEBUG: List the files in the ~/.ssh directory.
        echo "Directory contents of " $(pwd) ": " &&
        sudo ls -la
    # Step to write the contents of our "Repository secret" named "SSH_PRIVATE_KEY" to our temporary key file called "id_rsa.key".
    - name: Write SSH Private Key to id_rsa.key file
      run: |
        # Write the SSH private key from "Repository secrets" to the temporary id_rsa.key file.
        echo -e "${{ secrets.SSH_PRIVATE_KEY }}" | sudo tee ~/.ssh/id_rsa.key > /dev/null &&
        # DEBUG: Change to home directory
        cd ~ &&
        # DEBUG: Change to ~/.ssh directory inside home directory.
        cd .ssh &&
        # DEBUG: Display the path of the current directory.
        echo "Current directory is: " $(pwd) &&
        # DEBUG: List the files in the ~/.ssh directory to verify "id_rsa.key" was created.
        echo "Directory contents of " $(pwd) ": " &&
        sudo ls -la &&
        # DEBUG: Display the new contents of the id_rsa.key file. (It will be encrypted, but should be multiple lines of asterisks if correct.)
        echo "Contents of ~/.ssh/id_rsa.key: " &&
        sudo cat ~/.ssh/id_rsa.key
    # Step to change permission of the temporary id_rsa.key so SCP can use it.
    - name: Set permissions for SSH private key
      run: |
        # Set the permissions for the id_rsa.key file to 600.
        sudo chmod 600 /home/runner/.ssh/id_rsa.key
        # DEBUG: Change to the home directory.
        cd ~ &&
        # DEBUG: Change to ~/.ssh directory inside home directory.
        cd .ssh &&
        # DEBUG: Display the path of the current directory.
        echo "Current directory is: " $(pwd) &&
        # DEBUG: List the files in the ~/.ssh directory.
        echo "Directory contents of " $(pwd) ": " &&
        sudo ls -la
    # Final step to connect to the server/instance using SCP and the id_rsa.key file to transfer our files.
    - name: Connect to server/instance via SCP.
      run: |
        # SCP into server/instance. Before doing this, the directory on the server/instances needs to have permissions set for ```sudo chown -R <myUser>:<myUserGroup> /path/to/server/directory/```
        sudo scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.key /path/of/repo/directory/or/file.md serverUsername@<serverIPAddress>:/path/of/server/directory/
